### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by Yjohn** [Yjohn/research-project#1]
HTTP Headers

**Comment by wonmaungthein** [comment]
What should I do here?

**Comment by Yjohn** [comment]
hi won; i don't think you need to creat 2 file. i already created the
issue, so you can work on it
its my thought 💭
anyway first find out more information about the topics

**Comment by wonmaungthein** [comment]
Oh, I see.. Thank you.. I will try that.. :) . So, we just need to find out more information about the topic, right?
